BEGIN;
    CREATE EXTENSION "uuid-ossp";

    CREATE TABLE IF NOT EXISTS users (
        id uuid NOT NULL PRIMARY KEY DEFAULT uuid_generate_v4(),
        type INT GENERATED BY DEFAULT AS IDENTITY,
        name TEXT NOT NULL,
        email TEXT NOT NULL,
        ts TIMESTAMPTZ DEFAULT now(), 
        full_name TEXT,
        password TEXT,
        ts_mod TIMESTAMPTZ DEFAULT now(),
        credit INTEGER DEFAULT 0,
        state SMALLINT DEFAULT 0
    );
COMMIT;
